name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Deploy:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get version
        id: version
        run: echo "current=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
    
      - name: Build Frontend
        run: | 
          cd frontend
          npm ci
          npm run build

      - name: Build Backend
        run: |
          cd backend
          npm ci
          npm run build

      - name: Wrangler
        uses: cloudflare/wrangler-action@v3.8.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            KEY_SECRET
            ADMIN_ID
            ADMIN_SECRET
        env:
          KEY_SECRET: ${{ secrets.WORKER_KEY_SECRET }}
          ADMIN_ID: ${{ secrets.WORKER_ADMIN_ID }}
          ADMIN_SECRET: ${{ secrets.WORKER_ADMIN_SECRET }}
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.current }}
